#!/usr/bin/env python3
"""
Atlas OS — Profile Sync

Parses ide/src/modules/ai/lib/agents.ts and writes each built-in agent's
persona into vault/agents/{slug}/profile.md. The TS file is the single
source of truth; profile.md is generated and overwritten on each run.

Idempotent: re-running with no source changes produces no file diff.

Usage:
    python tools/sync_profiles.py
    python tools/sync_profiles.py --check   # exit 1 if profiles are stale
"""

import argparse
import re
import sys
from pathlib import Path

ROOT      = Path(__file__).resolve().parent.parent
AGENTS_TS = ROOT / "ide" / "src" / "modules" / "ai" / "lib" / "agents.ts"
AGENTS_DIR = ROOT / "vault" / "agents"

# Each BUILTIN entry: { id, name, description, icon, builtIn, instructions: `...` }
_ENTRY_RE = re.compile(
    r"\{\s*"
    r"id:\s*\"builtin:(?P<slug>[a-z0-9-]+)\"\s*,\s*"
    r"name:\s*\"(?P<name>[^\"]+)\"\s*,\s*"
    r"description:\s*\"(?P<description>[^\"]+)\"\s*,\s*"
    r"icon:\s*\"(?P<icon>[^\"]+)\"\s*,\s*"
    r"builtIn:\s*true\s*,\s*"
    r"instructions:\s*`(?P<instructions>[^`]*)`",
    re.DOTALL,
)


def _parse_agents(src: str) -> list[dict]:
    return [m.groupdict() for m in _ENTRY_RE.finditer(src)]


HEADER = (
    "<!-- AUTO-GENERATED by tools/sync_profiles.py — DO NOT EDIT.\n"
    "     Source: ide/src/modules/ai/lib/agents.ts -->\n"
)


def _format_profile(agent: dict) -> str:
    return (
        HEADER
        + "---\n"
        + f"agent: {agent['slug']}\n"
        + f"name: {agent['name']}\n"
        + f"icon: {agent['icon']}\n"
        + "---\n\n"
        + f"# {agent['name']}\n\n"
        + f"> {agent['description']}\n\n"
        + "## Instructions\n\n"
        + "```\n"
        + agent['instructions'].strip()
        + "\n```\n"
    )


def sync(check: bool = False) -> int:
    if not AGENTS_TS.exists():
        print(f"  Not found: {AGENTS_TS}", file=sys.stderr)
        return 1
    src = AGENTS_TS.read_text(encoding="utf-8")
    agents = _parse_agents(src)
    if not agents:
        print("  No built-in agents matched in agents.ts", file=sys.stderr)
        return 1

    drift = 0
    for agent in agents:
        slug = agent["slug"]
        office = AGENTS_DIR / slug
        office.mkdir(parents=True, exist_ok=True)
        target = office / "profile.md"
        new_content = _format_profile(agent)
        old_content = target.read_text(encoding="utf-8") if target.exists() else ""
        if new_content == old_content:
            print(f"  = {slug:<14}  up to date")
            continue
        drift += 1
        if check:
            print(f"  ! {slug:<14}  STALE")
        else:
            target.write_text(new_content, encoding="utf-8")
            print(f"  + {slug:<14}  written")

    if check and drift:
        print(f"\n  {drift} profile(s) stale — run: python tools/sync_profiles.py")
        return 1
    return 0


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Sync agent profiles from TS to vault")
    p.add_argument("--check", action="store_true",
                   help="Exit non-zero if any profile is out of sync, do not write")
    return p.parse_args()


if __name__ == "__main__":
    sys.exit(sync(check=_parse_args().check))
